# Use root/example as user/password credentials
version: '3.1'


services:
  db:
    container_name: mysql
    image: mysql
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${root_password}
    ports:
      - '3306:3306'

